dist: trusty
sudo: false

language: node_js
node_js:
  - "6"

before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb

script:
  - npm run lint
