version: 2
jobs:
  build:
    docker:
      - image: node:10.14.2-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "v2/package-lock.json" }}
            - v2-npm-
      - run: cd v2 && npm install
      - save_cache:
          key: v2-npm-{{ checksum "v2/package-lock.json" }}
          paths:
            - v2/node_modules

      - run: cd v2 && npm run build
      - run: cd v2 && npm run prettier -- --check
      - run: cd v2 && npm run lint
      - run: cd v2 && npm run test
      - run: |
          set -e
          curl -Lo /tmp/go.tgz https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
          tar -C /usr/local -xzf /tmp/go.tgz
          echo 'export PATH=/usr/local/go/bin:$PATH' >> $BASH_ENV
      - run: go test ./...
