version: 2
jobs:
  build:
    docker:
      - image: node:10.14.2-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "v2/package-lock.json" }}
            - v2-npm-
      - run: cd v2 && npm install
      - save_cache:
          key: v2-npm-{{ checksum "v2/package-lock.json" }}
          paths:
            - v2/node_modules

      - run: echo SKIP_PREFLIGHT_CHECK=true > v2/.env
      - run: cd v2 && npm run build
      - run: cd v2 && npm run prettier -- --check
      - run: cd v2 && npm run lint
      - run: cd v2 && npm run test
